### ISSUE TITLE
it's not work for my wacom ptk840, and photoshop 2019

### ISSUE THREAD

**Issue by lostsoundzz** [millionart/PhotoshopBrushRotateTool#1]
I bought it today, but it does not work, could you help me solve this problem...
the situation in my computer is:  
it only works in the first stroke,  then I use the same action,  it doesn't change the brush direction, only quickly pump up a brush setting windows(like  RMB click did)
and, also, I use  the shortcut key    ; ' ,  it does not work too  
Thanks a lot ,    here's  my mail : lostsoundzz@gmail.com

Adobe Photoshop Version: 2019
Operating System: Windows 10 64-bit
Version: 10 or greater 10.0.17763.1

**Comment by millionart** [comment]
What about restart Brush Roate Tool?
Will it happen again?

The pen and mouse operate differently (Pen crazy sending the left button), which sometimes disables the tool and needs to be restarted.
I will add this feature in the next version to temporarily alleviate this problem.

**Comment by lostsoundzz** [comment]
sure, thanks for your reply, I restart Brush Rotate Tool and try it again and again, I find a weird situation:
My Brush Rotate Tool 1.2 only works when I use a brush with angle 0,,, that's means, if I changed my brush angle already(it's not 0), After it,  It does not work at all,   
If I change it back to 0 by hands, Then It will work just 1 time again,,, it's very nosey, I could not use it continuously,, -_____-!!!!!    

just FYI, I use two monitors,  and I found it's only changed to angle 139, never the other angel buy BrushRotateTool

**Comment by millionart** [comment]
Which method have you used to change the angle?
B/E key? hot key? Right button?
Will all this bug or one?

**Comment by lostsoundzz** [comment]
None of them works, I try them all ,,
FYI, as before, every time I use hot key, it flicks out/closed a brush windows(like we use right click in photoshop),  but it not change the angle of my brush at all

Thank for your help again.....

millionart <notifications@github.com> 于2019年1月6日周日 下午8:05写道：

**Comment by millionart** [comment]
This is strange, if you don't use a pen, just use the mouse,Will it also fail?

**Comment by lostsoundzz** [comment]
I try to use my mouse, it does not work too,,   and I  try to use
(Optional) Apssistant.zip,  it give me a feedback as in pic below :
[image:http://thyrsi.com/t6/651/1546828317x2918528114.png]

millionart <notifications@github.com> 于2019年1月6日周日 下午9:16写道：

**Comment by millionart** [comment]
Email reply can't display image, please send to github.

**Comment by lostsoundzz** [comment]
![bug](https://user-images.githubusercontent.com/46425519/50746516-717e2000-11fd-11e9-984f-e250432e35e1.png)

**Comment by millionart** [comment]
The Apssistant zip package has lost some files and has been added.

**Comment by millionart** [comment]
Are you running any security software? Please temporarily disable and try, because BRotate simulates mouse and keyboard operations and may be disabled by such software.

**Comment by millionart** [comment]
I tested all possible methods of operation, guessing that you might have pressed the left button or the pen tip has touched the tablet before the spin button was released , which triggers a system-level bug that cannot be recovered before the tool is restarted.

This bug can't be fixed at the moment (very strange, only the problematic button will be completely unexecutable)

The correct way to do this software is
Hold the rotate button
Move the pointer (do not press the left button or click on the tablet with the pen)
Release the rotary button
Start automatic rotation
Allow to start painting

I have updated and uploaded the 1.3 version, please try it out.

**Comment by lostsoundzz** [comment]
Try it by your way,   still doesn't work, Thanks for your patient about replying me , 
and FYI, with new version 1.3,   still have the same bug "139" angle,  that means even I
click the rotary button (;'), it just rotates to 139 angles then stop function at all, that what's happening
in my computer...      if I use wacom table by your way, it will change my brush angle to 139, then stop rotate at all,, super-wired

**Comment by millionart** [comment]
Can you try to run on other computers?

**Comment by millionart** [comment]
Oh, sorry, it took so long, and I just released a new version to fix the bug. Please download the 1.4 version to try.

**Comment by millionart** [comment]
Duplicate of #2
